# Generated by Django 4.1.3 on 2024-03-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='lng',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
