# Generated by Django 4.1.3 on 2024-03-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_parkingslot_lat_parkingslot_lng_parkingslot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
