# Generated by Django 4.1.3 on 2024-03-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_parkingslot_lat_alter_parkingslot_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='name',
            field=models.TextField(null=True, unique=True),
        ),
    ]
