# Generated by Django 4.1.3 on 2024-03-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_parkingslot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='name',
        ),
    ]
