# Generated by Django 4.1.3 on 2024-03-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
